apiVersion: sql.databricks.crossplane.io/v1alpha1
kind: SQLGlobalConfig
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/sqlglobalconfig
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    dataAccessConfig:
      spark.sql.session.timeZone: UTC
    instanceProfileArn: arn:....
    securityPolicy: DATA_ACCESS_CONTROL
